### ISSUE TITLE
iOS Trail SDk

### ISSUE THREAD

**Issue by dimohamdy** [Wikitude/wikitude-titanium#26]
in iOS "TRAIL" word in screen and not example work

**Comment by AndreasSchacherbauerWikitude** [comment]
So your problem is that the TRIAL watermark appears and none of the examples is loading?
Can you please provide us with more information about your Titanium installation (version number), iOS version and iOS device?

**Comment by dimohamdy** [comment]
my Titanium SDK  3.4.1.GA and my iOS is 8.1

**Comment by pnagele** [comment]
Just released a new version of the sample app - please check whether this issue still exists, otherwise we gonna close this issue.
