### ISSUE TITLE
This Repository does not work on Android (Buyer Beware)

### ISSUE THREAD

**Issue by WillDent** [Wikitude/wikitude-titanium#41]
http://www.wikitude.com/developer/developer-forum/-/message_boards/message/851595

**Comment by WillDent** [comment]
I am adding here a movie of sample code not working and also showing that all permissions are in place on the Android device running 4.4.2..  This was built using Titanium SDK 5.1.2.GA with Android SDK 6  (23).

https://s3.amazonaws.com/uploads.hipchat.com/40457/273840/C1iiSgt0emCwmPT/wikitude.mp4

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi, our latest release from July 11, 2016 should work fine with the latest version of the Titanium SDK. Our example application now also includes support for Android 6 runtime permissions.
If you still encounter problems, please let us know.
